server:
  port : 9090

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:newsdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      indent_output: true

cache:
  eviction-time: 900000

thread-pool-size: 50

hacker-news-base-url: https://hacker-news.firebaseio.com/v0/
item-endpoint: item/{id}.json
best-stories-endpoint: beststories.json
user-endpoint: user/{username}.json